[package]
name = "rust-users"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-service = "2.0"
env_logger = "0.10"
mongodb = "2.3"
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "8.1"
futures-util = "0.3"
futures = "0.3.30"
